[build-system]
requires=["setuptools", "setuptools-scm"]
build-backend="setuptools.build_meta"

[project]
name="Conteneurisation-Orchestration"
version="1.4.2"
authors=[
    {name = "AGOSTINO Romeo"}, 
    {name = "BIGAND Theo"}, 
    {name = "DRAME Moussa"}, 
    {name = "AUDIBERT Mathieu"}
]
readme="README.md"
requires-python=">=3.10"
dependencies = [
    "pandas",
    "pymongo",
    "zensical",
    "numpy",
    "python-dotenv",
    "fastapi[standard]"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cfg*", "src*"]

[tool.pytest.ini_options]
pythonpath=["."]